<?xml version="1.0"?>
<package format="3">
  <name>image_converter_cpp</name>
  <version>0.0.0</version>
  <description>YUYV to BGR image converter node</description>
  <maintainer email="nalyence@todo.todo">nalyence</maintainer>
  <license>Apache-2.0</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <depend>rclcpp</depend>
  <depend>sensor_msgs</depend>
  <depend>cv_bridge</depend>

  <test_depend>ament_lint_auto</test_depend>
  <test_depend>ament_lint_common</test_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
